"/":
    controller: Pages
    action: default

"/liste_des_utilisateurs":
    controller: User
    action: list

"/ajouter_un_utilisateur":
    controller: Security
    action: add

"/enregistrer_un_utilisateur":
    controller: Security
    action: save

"/connexion":
    controller: Security
    action: login

"/deconnexion":
    controller: Security
    action: disconnect

"/mot_de_passe_oublie":
    controller: Security
    action: forgetPassword